pipeline:
  docker:
    group: docker-image
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-default-backend-amd64
    auto_tag: true
    when:
      event: tag

  docker-arm:
    group: docker-image
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    build_args:
      - arch=arm64
    repo: kontena/pharos-default-backend-arm64
    auto_tag: true
    when:
      event: tag
